spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/rjgc3243?serverTimezone=UTC&characterEncoding=utf8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: rjgc
    password: rjgc123
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
